name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Display the path py pwsh
      run: |
        echo "github.workspace is ${{ github.workspace }}."
        ls ${{ github.workspace }}
      shell: pwsh
    - name: CMake Build
      run: |
        cd ${{ github.workspace }}
        ls
        mkdir build
        cd build
        cmake --version
        cmake --DCMAKE_INSTALL_PREFIX\${{ github.workspace }} ../
        ls
      shell: pwsh
    - name: CMake Install
      run: |
        cd ${{ github.workspace }}/build
        ls
        make
      shell: pwsh
